version: "3.9"

networks:
  extractor-network:
    external: true

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: credistory
    ports:
      - "5432:5432"
    networks:
      - extractor-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d credistory"]
      interval: 3s
      timeout: 3s
      retries: 20
      start_period: 5s

  extractor:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:postgres@postgres:5432/credistory"
    networks:
      - extractor-network

